name: Reject PRs to main

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  reject:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull-request@v3
        with:
          comment: |
            ❌ Intentaste hacer un _pull request_ hacia `main`. Volvé a hacer el PR hacia la rama que te corresponde (la propia que tiene tu nombre y apellido).
